"""HTML / PDF / email brief generation for OEE Pulse."""

from __future__ import annotations

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any, Optional

from dotenv import load_dotenv

load_dotenv()


def build_html_brief(
    plant_name: str,
    oee_plant: dict[str, Any],
    insights: list[dict[str, Any]],
    pareto_rows: list[dict[str, Any]],
    reliability: dict[str, Any],
) -> str:
    insight_html = "".join(
        f"<li><strong>[{i.get('priority','').upper()}]</strong> {i.get('message','')}</li>"
        for i in insights[:8]
    )
    pareto_html = "".join(
        f"<tr><td>{r.get('cause')}</td><td>{r.get('downtime_minutes', 0):.0f}</td>"
        f"<td>{float(r.get('pct', 0))*100:.1f}%</td></tr>"
        for r in pareto_rows[:8]
    )
    mttr = reliability.get("mttr_min", "—")
    mtbf = reliability.get("mtbf_min", "—")
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>OEE Pulse Brief — {plant_name}</title>
<style>
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; color: #1e293b; margin: 24px; background: #f8fafc; }}
  .card {{ background: #fff; border: 1px solid #cbd5e1; border-radius: 8px; padding: 20px; margin-bottom: 16px; }}
  h1 {{ color: #0f172a; margin: 0 0 4px; }}
  .accent {{ color: #d97706; }}
  .metrics td {{ padding: 8px 16px 8px 0; font-size: 18px; }}
  table.pareto {{ border-collapse: collapse; width: 100%; }}
  table.pareto th, table.pareto td {{ border-bottom: 1px solid #e2e8f0; text-align: left; padding: 8px; }}
  .footer {{ color: #64748b; font-size: 12px; margin-top: 24px; }}
</style></head><body>
  <div class="card">
    <h1>OEE Pulse <span class="accent">Plant Brief</span></h1>
    <div>{plant_name} · {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC</div>
  </div>
  <div class="card">
    <h2>OEE Cockpit</h2>
    <table class="metrics">
      <tr>
        <td><strong>OEE</strong><br>{float(oee_plant.get('oee',0))*100:.1f}%</td>
        <td><strong>Availability</strong><br>{float(oee_plant.get('availability',0))*100:.1f}%</td>
        <td><strong>Performance</strong><br>{float(oee_plant.get('performance',0))*100:.1f}%</td>
        <td><strong>Quality</strong><br>{float(oee_plant.get('quality',0))*100:.1f}%</td>
      </tr>
    </table>
    <p>MTTR: {mttr} min · MTBF: {mtbf} min</p>
  </div>
  <div class="card">
    <h2>Manager Insights</h2>
    <ul>{insight_html or '<li>No insights generated.</li>'}</ul>
  </div>
  <div class="card">
    <h2>Downtime Pareto</h2>
    <table class="pareto">
      <thead><tr><th>Cause</th><th>Minutes</th><th>%</th></tr></thead>
      <tbody>{pareto_html or '<tr><td colspan="3">No downtime data</td></tr>'}</tbody>
    </table>
  </div>
  <div class="footer">Generated by OEE Pulse · Reduce unplanned downtime · Protect the schedule</div>
</body></html>"""


def write_html_report(html: str, out_dir: Path | str = "reports/output") -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"oee_pulse_brief_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.html"
    path.write_text(html, encoding="utf-8")
    return path


def _pdf_safe(text: str) -> str:
    """Map common Unicode to Latin-1-safe ASCII for Helvetica core fonts."""
    repl = {
        "\u2014": "-",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2022": "*",
        "\u00d7": "x",
        "\u2248": "~",
        "\u2192": "->",
    }
    out = str(text)
    for a, b in repl.items():
        out = out.replace(a, b)
    return out.encode("latin-1", errors="replace").decode("latin-1")


def write_pdf_report(html_summary: dict[str, Any], out_dir: Path | str = "reports/output") -> Path:
    """Lightweight PDF brief via fpdf2 (no browser dependency)."""
    from fpdf import FPDF

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"oee_pulse_brief_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "OEE Pulse Plant Brief", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(
        0,
        8,
        _pdf_safe(f"{html_summary.get('plant_name', 'Plant')}  |  {datetime.utcnow().isoformat()}Z"),
        ln=True,
    )
    pdf.ln(4)
    pdf.set_text_color(30, 41, 59)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "OEE Metrics", ln=True)
    pdf.set_font("Helvetica", "", 12)
    oee = html_summary.get("oee_plant", {})
    for label, key in [
        ("OEE", "oee"),
        ("Availability", "availability"),
        ("Performance", "performance"),
        ("Quality", "quality"),
    ]:
        pdf.cell(0, 7, f"{label}: {float(oee.get(key, 0))*100:.1f}%", ln=True)
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "Insights", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for i in html_summary.get("insights", [])[:6]:
        msg = _pdf_safe(str(i.get("message", ""))[:220])
        pdf.multi_cell(0, 6, _pdf_safe(f"- [{i.get('priority','')}] {msg}"))
        pdf.ln(1)
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "Top Downtime", ln=True)
    pdf.set_font("Helvetica", "", 11)
    for r in html_summary.get("pareto_rows", [])[:6]:
        pdf.cell(
            0,
            6,
            _pdf_safe(
                f"{r.get('cause')}: {float(r.get('downtime_minutes', 0)):.0f} min "
                f"({float(r.get('pct', 0))*100:.1f}%)"
            ),
            ln=True,
        )
    pdf.output(str(path))
    return path


def send_email_brief(
    html: str,
    subject: Optional[str] = None,
    demo_mode: Optional[bool] = None,
) -> dict[str, Any]:
    """Send HTML brief via SMTP, or simulate in demo mode."""
    if demo_mode is None:
        demo_mode = os.getenv("OEE_PULSE_DEMO_MODE", "true").lower() in {"1", "true", "yes"}

    to_addr = os.getenv("SMTP_TO", "plant.manager@example.com")
    from_addr = os.getenv("SMTP_FROM", "oee-pulse@example.com")
    subject = subject or f"OEE Pulse Daily Brief — {datetime.utcnow().strftime('%Y-%m-%d')}"

    if demo_mode:
        return {
            "ok": True,
            "demo": True,
            "message": f"Demo mode: email to {to_addr} simulated (not sent).",
            "subject": subject,
            "to": to_addr,
        }

    host = os.getenv("SMTP_HOST")
    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER")
    password = os.getenv("SMTP_PASSWORD")
    if not host:
        return {"ok": False, "error": "SMTP_HOST not configured"}

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(host, port, timeout=20) as server:
        server.starttls()
        if user and password:
            server.login(user, password)
        server.sendmail(from_addr, [to_addr], msg.as_string())

    return {"ok": True, "demo": False, "to": to_addr, "subject": subject}
